services:
  renderer:
    build: .
    shm_size: '2gb'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/public/cesium
      - ./output:/app/output
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: ["node", "bin/render.js"]
